apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-deployment
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: hospitalitycontainerregistry.azurecr.io/hospitality_emailservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: emailservice-service
spec:
  type: ClusterIP  
  selector:
    app: emailservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
