apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-deployment
  labels:
    app: healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcheck
  template:
    metadata:
      labels:
        app: healthcheck
    spec:
      containers:
      - name: healthcheck 
        image: hospitalitycontainerregistry.azurecr.io/hospitality_healthcheck:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: healthcheck-service
spec:
  type: NodePort 
  selector:
    app: healthcheck
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30401
