apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
  labels:
    app: patient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient 
        image: hospitalitycontainerregistry.azurecr.io/hospitality_patient:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  type: ClusterIP  
  selector:
    app: patient
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
